#ifndef DRIVERS_BSP_STM32F7XX_NUCLEO_INC_NUCLEO_UART_H_
#define DRIVERS_BSP_STM32F7XX_NUCLEO_INC_NUCLEO_UART_H_

void nucleo_uart_init();

#endif /* DRIVERS_BSP_STM32F7XX_NUCLEO_INC_NUCLEO_UART_H_ */
